// A massive database of useless facts.
// "Quantity over quality" - Our Motto.
// Now strictly curated to ensure maximum sarcasm and technical correctness.

const USELESS_FACTS_DB = [
  "Bananas can't walk. Do what you want with this information.",
  "Fish don't sneeze. Probably.",
  "Your pillow knows too much about your sleep schedule.",
  "Grass grows. Slowly. Shocking.",
  "The sun is hot. Groundbreaking information.",
  "99% of socks disappear in the washing machine dimension.",
  "Ants don't pay taxes.",
  "Your left shoe has trust issues.",
  "Water is wet, unless it's ice, then it's hard water.",
  "Breathing is mandatory for survival.",
  "You are currently reading this text.",
  "The floor is made of floor.",
  "Mirrors are just glass with an ego.",
  "Silence is loud if you listen hard enough.",
  "Ducks have no idea they are ducks.",
  "You can't hum while holding your nose.",
  "Every odd number has an 'e' in it.",
  "Sand is just small rocks with commitment issues.",
  "The alphabet is in that order because we said so.",
  "Your skeleton is wet.",
  "You have never seen your own face, only reflections and pictures.",
  "Clapping is just hitting yourself because you like something.",
  "Pineapples do not belong on pizza. Or maybe they do. I'm a script.",
  "Llamas are just long sheep.",
  "If you clean a vacuum cleaner, you become a vacuum cleaner.",
  "A straw has only one hole.",
  "You can't imagine a new color.",
  "There is a skeleton inside you right now.",
  "Your future self is watching you right now through memories.",
  "Bees do not care about your credit score.",
  "Clouds are heavy. Like, really heavy.",
  "You can't tickle yourself. Unless you are weird.",
  "The brain named itself.",
  "Lasagna is just spaghetti flavored cake.",
  "Ice cubes are swimming in their own blood.",
  "You swap a little bit of air with everyone you meet.",
  "Sloths are not lazy, they are energy efficient.",
  "Cucumbers are 96% water and 4% crunch.",
  "Every time you paint a room, it gets slightly smaller.",
  "Keys are just jagged metal that we trust with our lives.",
  "Pockets are just bags sewn into your pants.",
  "You are the engine of your bicycle.",
  "Technically, you are always touching your clothes.",
  "Shadows move faster than you do.",
  "Your stomach thinks all potatoes are mashed.",
  "If you rip a hole in a net, there are fewer holes in it.",
  "Cheese is just milk that gave up on its dreams and got hard.",
  "A fork is just a spoon with anxiety.",
  "Is the S or C silent in Scent?",
  "Your nose is always in your peripheral vision.",
  "Paper cuts are the trees' way of fighting back.",
  "Elevators are just vertical trains.",
  "Nothing is on fire, fire is on things.",
  "Oranges are pre-sliced by nature.",
  "If you wait for the waiter, you become the waiter.",
  "A different version of you exists in the minds of everyone who knows you.",
  "You can't stand backwards on stairs.",
  "Lobsters are mermaids to scorpions.",
  "Hot water sounds different than cold water when you pour it.",
  "Your toes are just finger stubs.",
  "Bridges are just roads over nothing.",
  "Umbrellas are just rain shields.",
  "Gloves are socks for your hands.",
  "Your bed is a wireless charger for your body.",
  "Milk is just liquid meat if you think about it too hard.",
  "Your shadow has never seen the sun.",
  "Every mirror you buy is in used condition.",
  "You can't say 'M' without your lips touching.",
  "The word 'swims' is the same upside down.",
  "Intentionally losing a game of rock, paper, scissors is just as hard as trying to win.",
  "You have never been in an empty room.",
  "Your tongue is the only muscle in your body attached at only one end.",
  "If you were invisible, you would be blind because light would pass through your eyes.",
  "Honey is the only food that doesn't spoil. It just gets weird.",
  "The average cloud weighs about 1.1 million pounds.",
  "Wombat poop is cube-shaped. Why? Geometry.",
  "It is impossible to lick your own elbow. You just tried it.",
  "Hippopotamus milk is pink.",
  "A shrimp's heart is in its head.",
  "It is physically impossible for pigs to look up into the sky.",
  "If you sneeze too hard, you could fracture a rib.",
  "Wearing headphones for just an hour could increase the bacteria in your ear by 700 times.",
  "Cat urine glows under a black-light.",
  "Like fingerprints, everyone's tongue print is different.",
  "Rubber bands last longer when refrigerated.",
  "There are 293 ways to make change for a dollar.",
  "The average person's left hand does 56% of the typing.",
  "A shark is the only fish that can blink with both eyes.",
  "Dreamt is the only English word that ends in the letters 'mt'.",
  "Almonds are a member of the peach family.",
  "Maine is the only state that has a one-syllable name.",
  "A cat has 32 muscles in each ear.",
  "An ostrich's eye is bigger than its brain.",
  "Tigers have striped skin, not just striped fur.",
  "Most people fall asleep in seven minutes.",
  "'Stewardesses' is the longest word typed with only the left hand.",
  "No word in the English language rhymes with month, orange, silver, or purple.",
  "Typewriter is the longest word that can be made using the letters only on one row of the keyboard.",
  "The electric chair was invented by a dentist.",
  "A snail can sleep for three years.",
  "A crocodile cannot stick its tongue out.",
  "Butterflies taste with their feet.",
  "Elephants are the only animal that cannot jump.",
  "Women blink nearly twice as much as men.",
  "The population of the earth is about 8 billion. You are just one.",
  "Your thumb is the same length as your nose.",
  "You just touched your nose to check.",
  "Banging your head against a wall uses 150 calories an hour.",
  "Humans and bananas share about 50% of the same DNA.",
  "A zebra is white with black stripes.",
  "The cigarette lighter was invented before the match.",
  "A duck's quack doesn't echo, and no one knows why.",
  "Most dust particles in your house are made from dead skin.",
  "If you keep a goldfish in a dark room, it will turn pale.",
  "The name of all the continents end with the same letter that they start with.",
  "It is impossible to sneeze with your eyes open.",
  "Every human spent about half an hour as a single cell.",
  "Toilet paper was invented in China.",
  "Ketchup was sold in the 1830s as medicine.",
  "There are more lifeforms living on your skin than there are people on the planet.",
  "A tarantula can live without food for two years.",
  "You burn more calories sleeping than you do watching television.",
  "Apples wake you up better than coffee.",
  "The first alarm clock could only ring at 4 a.m.",
  "Birds don't urinate.",
  "A blue whale's tongue weighs as much as an elephant.",
  "Polar bears are left-handed.",
  "A flea can jump 350 times its body length.",
  "A starfish has no brain.",
  "The average person has over 1,460 dreams a year.",
  "Ants never sleep. Also they don't have lungs.",
  "When the moon is directly overhead, you will weigh slightly less.",
  "A Mole can dig a tunnel 300 feet long in just one night.",
  "The Earth is the only planet not named after a God.",
  "It takes about 8 minutes for light from the Sun to reach Earth.",
  "Some worms will eat themselves if they can't find any food.",
  "Dolphins sleep with one eye open.",
  "The world's oldest piece of chewing gum is over 9,000 years old.",
  "The Queen of England has two birthdays.",
  "Bolivia has two capitals.",
  "The only letter that doesn't appear on the periodic table is J.",
  "Golf balls have 336 dimples.",
  "The moon has moonquakes.",
  "There are more stars in space than there are grains of sand on every beach in the world.",
  "A day on Venus is longer than a year on Venus.",
  "You can't burp in space.",
  "Cheetahs can't roar. They meow like house cats.",
  "The unicorn is the national animal of Scotland.",
  "Bees can fly higher than Mount Everest.",
  "The Eiffel Tower can be 15 cm taller during the summer.",
  "Australia is wider than the moon.",
  "Venus is the only planet to spin clockwise.",
  "Nutmeg is a hallucinogen.",
  "The hashtag symbol is technically called an octothorpe.",
  "The 100 folds in a chef's hat represent 100 ways to cook an egg.",
  "Some cats are allergic to humans.",
  "The small pocket in your jeans was designed for pocket watches.",
  "Pringles aren't actually potato chips.",
  "Cotton candy was invented by a dentist.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "Space smells like seared steak.",
  "The tiny plastic thing at the end of a shoelace is called an aglet.",
  "Octopuses have blue blood.",
  "A group of flamingos is called a 'flamboyance'.",
  "A group of pugs is called a 'grumble'.",
  "A group of crows is called a 'murder'.",
  "The infinity sign is called a lemniscate.",
  "The dot over the letter 'i' is called a tittle.",
  "The space between your eyebrows is called the glabella.",
  "The plastic table in the middle of a pizza box is called a box tent.",
  "The metal part at the end of a pencil is called a ferrule.",
  "The smell of rain is called petrichor.",
  "The rumble in your stomach is called a wamble.",
  "The feeling of being watched is called scopaesthesia.",
  "The day after tomorrow is called overmorrow.",
  "The clean smell after a thunderstorm is caused by ozone.",
  "There are more fake flamingos in the world than real ones.",
  "Scotland has 421 words for snow.",
  "Armadillos are bulletproof.",
  "Firefighters use wetting agents to make water wetter.",
  "In 2014, there was a Tinder match in Antarctica.",
  "The high heeled shoe was originally designed for men.",
  "Sliced bread was invented in 1928.",
  "The lighter was invented in 1823.",
  "Matches were invented in 1826.",
  "So the lighter was invented before matches.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "The average person spends 6 months of their lifetime waiting for red lights to turn green.",
  "You are always clapping, the intervals just vary.",
  "Toes are just thumb feet.",
  "Your tongue fits perfectly in your mouth. You're thinking about it now.",
  "You can't breathe through your nose with your tongue out.",
  "You just tried to breathe through your nose with your tongue out.",
  "You looked like a dog when you did that.",
  "You are smiling because you got tricked.",
  "The word 'queue' is just 'Q' followed by four silent letters waiting in line.",
  "If you drop soap on the floor, is the floor clean or is the soap dirty?",
  "Beetles taste like apples, wasps like pine nuts, and worms like fried bacon.",
  "A single cloud can weigh more than a million pounds.",
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
  "Cherophobia is the fear of fun.",
  "Human teeth are the only part of the body that cannot heal themselves.",
  "A cow gives nearly 200,000 glasses of milk in a lifetime.",
  "Bats always turn left when exiting a cave.",
  "The eye of an ostrich is bigger than its brain.",
  "Frogs cannot vomit. If one absolutely has to, then it vomits its entire stomach.",
  "It is impossible to tickle yourself.",
  "The average person walks the equivalent of five times around the world in a lifetime.",
  "Men get hiccups more often than women.",
  "A King Cobra has enough poison to kill an elephant.",
  "The hummingbird is the only bird that can fly backwards.",
  "A cat's jaw cannot move sideways.",
  "If you lift a kangaroo's tail off the ground it can't hop.",
  "A baby octopus is about the size of a flea when it is born.",
  "A sheep, a duck and a rooster were the first passengers in a hot air balloon.",
  "Recycling one glass jar saves enough energy to watch TV for 3 hours.",
  "Owls represent intelligence, but they are actually kind of dumb.",
  "If you yelled for 8 years, 7 months and 6 days you would have produced enough sound energy to heat one cup of coffee.",
  "Banging your head against a wall for one hour burns 150 calories.",
  "The ant can lift 50 times its own weight.",
  "A tiger's legs are so powerful that they can remain standing even when dead.",
  "The flea can jump 350 times its body length. It's like a human jumping the length of a football field.",
  "A cat has 32 muscles in each ear.",
  "An elephant’s trunk has no bones but 40,000 muscles.",
  "A garden caterpillar has 248 muscles in its head.",
  "A ladybug can fly at speeds up to 37 miles per hour.",
  "There are more than 1,000 kinds of bats in the world.",
  "A housefly hums in the key of F.",
  "A group of 12 or more cows is called a flink.",
  "A group of frogs is called an army.",
  "A group of rhinos is called a crash.",
  "A group of kangaroos is called a mob.",
  "A group of whales is called a pod.",
  "A group of geese is called a gaggle.",
  "A group of owls is called a parliament.",
  "The shark is the only fish that can blink with both eyes.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The chicken came before the egg. According to the Bible, Genesis 1:20-22.",
  "Slugs have 4 noses.",
  "Starfish have no brains.",
  "Mosquitoes have 47 teeth.",
  "Polar bears have black skin.",
  "A camel has 3 eyelids.",
  "A giraffe's tongue is black.",
  "A goldfish has a memory span of 3 seconds.",
  "A chameleon's tongue is twice the length of its body.",
  "An iguana can stay under water for 28 minutes.",
  "A shark's teeth are as hard as steel.",
  "A lobster's blood is colorless but when exposed to oxygen it turns blue.",
  "Armadillos have 4 babies at a time and they are all the same sex.",
  "Reindeer like bananas.",
  "A bird's heart beats 400 times per minute while resting.",
  "A blue whale's heart is the size of a small car.",
  "A cockroach will live 9 days without its head before it starves to death.",
  "A butterfly has 12,000 eyes.",
  "A dragonfly has a lifespan of 24 hours.",
  "A jellyfish is 95% water.",
  "A starfish can grow a whole new body from just one arm.",
  "A sea horse is the only male animal that gets pregnant.",
  "An electric eel can produce a shock of up to 600 volts.",
  "A scallop has 35 blue eyes.",
  "A shrimp has 5 pairs of legs.",
  "A mussel has a beard.",
  "A clam has a foot.",
  "A squid has 10 tentacles.",
  "An octopus has 3 hearts.",
  "A snail can sleep for 3 years.",
  "A worm has 5 hearts.",
  "A leech has 32 brains.",
  "A spider has transparent blood.",
  "A scorpion glows under ultraviolet light.",
  "A bee has 5 eyes.",
  "A mosquito has 47 teeth.",
  "A fly vomits on its food before eating it.",
  "A butterfly tastes with its feet.",
  "A cricket's ears are on its front legs.",
  "A grasshopper can jump 20 times its body length.",
  "A praying mantis is the only insect that can turn its head.",
  "A termite queen can lay 40,000 eggs a day.",
  "A worker bee produces about 1/12th of a teaspoon of honey in its lifetime.",
  "A queen bee can lay 1,500 eggs a day.",
  "A bee beats its wings 200 times a second.",
  "A wasp can sting multiple times.",
  "A hornet's sting is more painful than a wasp's sting.",
  "A fire ant bite feels like a burn.",
  "A tick can grow to 4 times its size when full of blood.",
  "A bed bug can live for a year without feeding.",
  "A dust mite feeds on dead skin cells.",
  "A louse can hold its breath for 8 hours."
];

export const generateUselessFact = async (): Promise<string> => {
  // Simulate processing time to make it feel like "work" is being done
  await new Promise(resolve => setTimeout(resolve, 1200));

  // Strictly return from the curated DB. No more nonsense generation.
  return USELESS_FACTS_DB[Math.floor(Math.random() * USELESS_FACTS_DB.length)];
};

export const generateFeaturedFacts = async (): Promise<string[]> => {
  const shuffled = [...USELESS_FACTS_DB].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, 6);
};
